# Generated by Django 6.0.3 on 2026-03-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pass_mark',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='examresult',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('ESSAY', 'Essay')], default='MCQ', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='required_keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
