# Generated by Django 6.0.2 on 2026-04-29 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_avatar'),
        ('core', '0009_pendingemailchange'),
    ]

    operations = [
    ]
