# Generated by Django 6.0.2 on 2026-04-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_profile_avatar_profile_is_2fa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginapproval',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
