# Generated by Django 6.0.2 on 2026-04-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginapproval',
            name='code',
            field=models.CharField(default='', max_length=6),
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
